**Principal component analysis**

In [1]:
from sklearn.decomposition import PCA
import numpy as np

In [3]:
# Create a sample dataset
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Create an instance of PCA with the desired number of components
n_components = 2
pca = PCA(n_components=n_components)


In [4]:
# Fit the PCA model to the data
pca.fit(X)

# Get the principal components
principal_components = pca.components_


In [5]:
# Get the explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Transform the data to the lower-dimensional space
X_transformed = pca.transform(X)


In [6]:

print("Principal Components:")
print(principal_components)

print("Explained Variance Ratio:")
print(explained_variance_ratio)

print("Transformed Data:")
print(X_transformed)

Principal Components:
[[ 0.57735027  0.57735027  0.57735027]
 [ 0.         -0.70710678  0.70710678]]
Explained Variance Ratio:
[1. 0.]
Transformed Data:
[[-7.79422863e+00 -1.77635684e-15]
 [-2.59807621e+00 -4.44089210e-16]
 [ 2.59807621e+00  4.44089210e-16]
 [ 7.79422863e+00  1.77635684e-15]]
